import SummaryModal from './modals/SummaryModal';
import QRModal from './modals/QRModal';
import MilestoneModal from './modals/MilestoneModal';
import DetailsModal from './modals/DetailsModal';
import './Modals.css';

export default function Modals({ modal, onClose }) {
  const overlayVisible = modal.type !== null;

  const summaryContent = {
    available: {
      title: 'Available',
      description: 'Total available to ZDA for use.'
    },
    requested: {
      title: 'Requested',
      description: 'Total requested by ZDA.'
    },
    received: {
      title: 'Received',
      description: 'Total granted to ZDA.'
    },
    spent: {
      title: 'Spent',
      description: 'Total used to advance all projects.'
    },
    earned: {
      title: 'Earned',
      description: 'Total generated by all projects.'
    }
  };

  const isBasicSummary = Object.keys(summaryContent).includes(modal.type);
  const content = summaryContent[modal.type];

  return (
    <>
      {overlayVisible && (
        <div className="modal-overlay" onClick={onClose}></div>
      )}

      {modal.type === 'summary' && (
        <SummaryModal data={modal.data} onClose={onClose} />
      )}
      {modal.type === 'qr' && (
        <QRModal data={modal.data} onClose={onClose} />
      )}
      {modal.type === 'milestone' && (
        <MilestoneModal data={modal.data} onClose={onClose} />
      )}
      {modal.type === 'details' && (
        <DetailsModal data={modal.data} onClose={onClose} />
      )}

      {isBasicSummary && (
        <div className="modal-content-box" onClick={(e) => e.stopPropagation()}>
          <button className="close-button" onClick={onClose}>×</button>
          <h2>{content.title}</h2>
          <p>{content.description}</p>
        </div>
      )}
    </>
  );
}
